"""add venue table attribute

Revision ID: 15cb4974b134
Revises: f24f0509d292
Create Date: 2025-07-28 17:50:39.177394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15cb4974b134'
down_revision: Union[str, None] = 'f24f0509d292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('image_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'image_url')
    # ### end Alembic commands ###
