# """create posts table with shortcode

# Revision ID: 5f5f70a494a1
# Revises: a458ce15e159
# Create Date: 2025-05-10 18:31:02.246290

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import mysql

# # revision identifiers, used by Alembic.
# revision: str = '5f5f70a494a1'
# down_revision: Union[str, None] = 'a458ce15e159'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('bands')
#     op.drop_index('ix_performances_id', table_name='performances')
#     op.drop_table('performances')
#     op.drop_table('user_performances_favorite')
#     op.drop_table('user_artists_favorite')
#     op.drop_index('ix_users_id', table_name='users')
#     op.drop_index('ix_users_kakao_id', table_name='users')
#     op.drop_table('users')
#     op.drop_index('ix_artists_id', table_name='artists')
#     op.drop_table('artists')
#     op.drop_table('venues')
#     op.drop_table('user_performances_ticketalarm')
#     op.drop_table('performance_artists')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('performance_artists',
#     sa.Column('performance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#     sa.Column('artist_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#     sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='performance_artists_ibfk_2'),
#     sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], name='performance_artists_ibfk_1'),
#     sa.PrimaryKeyConstraint('performance_id', 'artist_id'),
#     mysql_collate='utf8mb4_unicode_ci',
#     mysql_default_charset='utf8mb4',
#     mysql_engine='InnoDB'
#     )
#     op.create_table('user_performances_ticketalarm',
#     sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#     sa.Column('performance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#     sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], name='user_performances_ticketalarm_ibfk_2'),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_performances_ticketalarm_ibfk_1'),
#     sa.PrimaryKeyConstraint('user_id', 'performance_id'),
#     mysql_collate='utf8mb4_unicode_ci',
#     mysql_default_charset='utf8mb4',
#     mysql_engine='InnoDB'
#     )
#     op.create_table('venues',
#     sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
#     sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
#     sa.Column('address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
#     sa.Column('instagram_account', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
#     sa.PrimaryKeyConstraint('id'),
#     mysql_collate='utf8mb4_unicode_ci',
#     mysql_default_charset='utf8mb4',
#     mysql_engine='InnoDB'
#     )
#     op.create_table('artists',
#     sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
#     sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
#     sa.Column('genre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
#     sa.Column('spotify_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
#     sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
#     sa.Column('instagram_account', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
#     sa.Column('band_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['band_id'], ['bands.id'], name='artists_ibfk_1'),
#     sa.PrimaryKeyConstraint('id'),
#     mysql_collate='utf8mb4_unicode_ci',
#     mysql_default_charset='utf8mb4',
#     mysql_engine='InnoDB'
#     )
#     op.create_index('ix_artists_id', 'artists', ['id'], unique=False)
#     op.create_table('users',
#     sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
#     sa.Column('kakao_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
#     sa.Column('nickname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
#     sa.Column('created_at', mysql.DATETIME(), nullable=True),
#     sa.PrimaryKeyConstraint('id'),
#     mysql_collate='utf8mb4_unicode_ci',
#     mysql_default_charset='utf8mb4',
#     mysql_engine='InnoDB'
#     )
#     op.create_index('ix_users_kakao_id', 'users', ['kakao_id'], unique=True)
#     op.create_index('ix_users_id', 'users', ['id'], unique=False)
#     op.create_table('user_artists_favorite',
#     sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#     sa.Column('artist_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#     sa.Column('created_at', mysql.DATETIME(), nullable=True),
#     sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='user_artists_favorite_ibfk_2'),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_artists_favorite_ibfk_1'),
#     sa.PrimaryKeyConstraint('user_id', 'artist_id'),
#     mysql_collate='utf8mb4_unicode_ci',
#     mysql_default_charset='utf8mb4',
#     mysql_engine='InnoDB'
#     )
#     op.create_table('user_performances_favorite',
#     sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#     sa.Column('performance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
#     sa.Column('created_at', mysql.DATETIME(), nullable=True),
#     sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], name='user_performances_favorite_ibfk_2'),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_performances_favorite_ibfk_1'),
#     sa.PrimaryKeyConstraint('user_id', 'performance_id'),
#     mysql_collate='utf8mb4_unicode_ci',
#     mysql_default_charset='utf8mb4',
#     mysql_engine='InnoDB'
#     )
#     op.create_table('performances',
#     sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
#     sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
#     sa.Column('venue_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
#     sa.Column('date', sa.DATE(), nullable=True),
#     sa.Column('time', mysql.TIME(), nullable=True),
#     sa.Column('ticket_open_date', sa.DATE(), nullable=True),
#     sa.Column('ticket_open_time', mysql.TIME(), nullable=True),
#     sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
#     sa.Column('ticket_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300), nullable=True),
#     sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300), nullable=True),
#     sa.Column('created_at', mysql.DATETIME(), nullable=True),
#     sa.Column('is_canceled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='performances_ibfk_1'),
#     sa.PrimaryKeyConstraint('id'),
#     mysql_collate='utf8mb4_unicode_ci',
#     mysql_default_charset='utf8mb4',
#     mysql_engine='InnoDB'
#     )
#     op.create_index('ix_performances_id', 'performances', ['id'], unique=False)
#     op.create_table('bands',
#     sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
#     sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
#     sa.Column('genre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
#     sa.Column('spotify_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
#     sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
#     sa.Column('instagram_account', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
#     sa.PrimaryKeyConstraint('id'),
#     mysql_collate='utf8mb4_unicode_ci',
#     mysql_default_charset='utf8mb4',
#     mysql_engine='InnoDB'
#     )
#     # ### end Alembic commands ###
