"""add venue attribute

Revision ID: 6368804e031e
Revises: 15cb4974b134
Create Date: 2025-07-28 18:53:38.445648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6368804e031e'
down_revision: Union[str, None] = '15cb4974b134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('venue', sa.Column('longitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'longitude')
    op.drop_column('venue', 'latitude')
    # ### end Alembic commands ###
