"""add review_likes relationship

Revision ID: 674e14e1d604
Revises: bad09ae13596
Create Date: 2025-09-23 10:12:16.005949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '674e14e1d604'
down_revision: Union[str, None] = 'bad09ae13596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magazine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magazine_id'), 'magazine', ['id'], unique=False)
    op.create_table('magazine_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magazine_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('text', 'image', 'quote', 'embed', 'divider', name='mag_block_type'), server_default='text', nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('align', sa.Enum('left', 'center', 'right', name='mag_img_align'), server_default='center', nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['magazine_id'], ['magazine.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magazine_block_magazine_id'), 'magazine_block', ['magazine_id'], unique=False)
    op.add_column('review', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.alter_column('review', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_constraint(op.f('review_ibfk_2'), 'review', type_='foreignkey')
    op.drop_constraint(op.f('review_ibfk_1'), 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'venue', ['venue_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('review', 'is_reported')
    op.drop_column('review', 'title')
    op.drop_column('review', 'performance_id')
    op.add_column('review_image', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_review_image_review_id'), 'review_image', ['review_id'], unique=False)
    op.drop_constraint(op.f('review_image_ibfk_1'), 'review_image', type_='foreignkey')
    op.create_foreign_key(None, 'review_image', 'review', ['review_id'], ['id'], ondelete='CASCADE')
    op.add_column('review_like', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('unique_user_review_like'), table_name='review_like')
    op.create_index(op.f('ix_review_like_review_id'), 'review_like', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_like_user_id'), 'review_like', ['user_id'], unique=False)
    op.create_unique_constraint('uq_review_like_review_user', 'review_like', ['review_id', 'user_id'])
    op.drop_constraint(op.f('review_like_ibfk_2'), 'review_like', type_='foreignkey')
    op.drop_constraint(op.f('review_like_ibfk_1'), 'review_like', type_='foreignkey')
    op.create_foreign_key(None, 'review_like', 'review', ['review_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review_like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_like', type_='foreignkey')
    op.drop_constraint(None, 'review_like', type_='foreignkey')
    op.create_foreign_key(op.f('review_like_ibfk_1'), 'review_like', 'review', ['review_id'], ['id'])
    op.create_foreign_key(op.f('review_like_ibfk_2'), 'review_like', 'user', ['user_id'], ['id'])
    op.drop_constraint('uq_review_like_review_user', 'review_like', type_='unique')
    op.drop_index(op.f('ix_review_like_user_id'), table_name='review_like')
    op.drop_index(op.f('ix_review_like_review_id'), table_name='review_like')
    op.create_index(op.f('unique_user_review_like'), 'review_like', ['user_id', 'review_id'], unique=True)
    op.drop_column('review_like', 'created_at')
    op.drop_constraint(None, 'review_image', type_='foreignkey')
    op.create_foreign_key(op.f('review_image_ibfk_1'), 'review_image', 'review', ['review_id'], ['id'])
    op.drop_index(op.f('ix_review_image_review_id'), table_name='review_image')
    op.drop_column('review_image', 'created_at')
    op.add_column('review', sa.Column('performance_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('review', sa.Column('title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=False))
    op.add_column('review', sa.Column('is_reported', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(op.f('review_ibfk_1'), 'review', 'performance', ['performance_id'], ['id'])
    op.create_foreign_key(op.f('review_ibfk_2'), 'review', 'user', ['user_id'], ['id'])
    op.alter_column('review', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('review', 'venue_id')
    op.drop_index(op.f('ix_magazine_block_magazine_id'), table_name='magazine_block')
    op.drop_table('magazine_block')
    op.drop_index(op.f('ix_magazine_id'), table_name='magazine')
    op.drop_table('magazine')
    # ### end Alembic commands ###
