"""Add id column to stamp table

Revision ID: 8bd4603eb81e
Revises: f65a67fd7cee
Create Date: 2025-09-21 13:48:49.548858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd4603eb81e'
down_revision: Union[str, None] = 'f65a67fd7cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stamp', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_stamp_id'), 'stamp', ['id'], unique=False)
    op.create_unique_constraint('unique_user_performance', 'stamp', ['user_id', 'performance_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_performance', 'stamp', type_='unique')
    op.drop_index(op.f('ix_stamp_id'), table_name='stamp')
    op.drop_column('stamp', 'id')
    # ### end Alembic commands ###
