"""add review_image and review_like

Revision ID: bad09ae13596
Revises: 8bd4603eb81e
Create Date: 2025-09-22 23:00:02.538496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad09ae13596'
down_revision: Union[str, None] = '8bd4603eb81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_image_id'), 'review_image', ['id'], unique=False)
    op.create_index(op.f('ix_review_image_review_id'), 'review_image', ['review_id'], unique=False)
    op.create_table('review_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'user_id', name='uq_review_like_review_user')
    )
    op.create_index(op.f('ix_review_like_id'), 'review_like', ['id'], unique=False)
    op.create_index(op.f('ix_review_like_review_id'), 'review_like', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_like_user_id'), 'review_like', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_like_user_id'), table_name='review_like')
    op.drop_index(op.f('ix_review_like_review_id'), table_name='review_like')
    op.drop_index(op.f('ix_review_like_id'), table_name='review_like')
    op.drop_table('review_like')
    op.drop_index(op.f('ix_review_image_review_id'), table_name='review_image')
    op.drop_index(op.f('ix_review_image_id'), table_name='review_image')
    op.drop_table('review_image')
    # ### end Alembic commands ###
