"""init

Revision ID: bc4df0c6e40d
Revises: 
Create Date: 2025-10-02 02:50:28.147439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4df0c6e40d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('spotify_url', sa.String(length=300), nullable=True),
    sa.Column('instagram_account', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_id'), 'artist', ['id'], unique=False)
    op.create_index(op.f('ix_artist_name'), 'artist', ['name'], unique=False)
    op.create_table('magazine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magazine_id'), 'magazine', ['id'], unique=False)
    op.create_table('mood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mood_id'), 'mood', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kakao_id', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('profile_url', sa.String(length=300), nullable=True),
    sa.Column('alarm_enabled', sa.Boolean(), nullable=False),
    sa.Column('location_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_kakao_id'), 'user', ['kakao_id'], unique=True)
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('instagram_account', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_id'), 'venue', ['id'], unique=False)
    op.create_table('magazine_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magazine_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('text', 'image', 'quote', 'embed', 'divider', name='mag_block_type'), server_default='text', nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('align', sa.Enum('left', 'center', 'right', name='mag_img_align'), server_default='center', nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['magazine_id'], ['magazine.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magazine_block_magazine_id'), 'magazine_block', ['magazine_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link_url', sa.String(length=300), nullable=True),
    sa.Column('payload_json', sa.String(length=64), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type', 'payload_json', name='uq_notification_user_type_payload')
    )
    op.create_index('ix_notification_user_created', 'notification', ['user_id', 'created_at'], unique=False)
    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('ticket_open_date', sa.Date(), nullable=True),
    sa.Column('ticket_open_time', sa.Time(), nullable=True),
    sa.Column('price', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('shortcode', sa.String(length=100), nullable=True),
    sa.Column('detail_url', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_id'), 'performance', ['id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    op.create_table('user_artist_ticketalarm',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'artist_id')
    )
    op.create_table('user_favorite_artist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'artist_id')
    )
    op.create_table('mood_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mood_id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mood_id'], ['mood.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performance_id'], ['performance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mood_id', 'performance_id', name='uq_mood_performance')
    )
    op.create_index('ix_mood_id_created_at', 'mood_recommendation', ['mood_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_mood_recommendation_id'), 'mood_recommendation', ['id'], unique=False)
    op.create_table('performance_artist',
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['performance_id'], ['performance.id'], ),
    sa.PrimaryKeyConstraint('performance_id', 'artist_id')
    )
    op.create_table('review_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_image_id'), 'review_image', ['id'], unique=False)
    op.create_index(op.f('ix_review_image_review_id'), 'review_image', ['review_id'], unique=False)
    op.create_table('review_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'user_id', name='uq_review_like_review_user')
    )
    op.create_index(op.f('ix_review_like_id'), 'review_like', ['id'], unique=False)
    op.create_index(op.f('ix_review_like_review_id'), 'review_like', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_like_user_id'), 'review_like', ['user_id'], unique=False)
    op.create_table('stamp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['performance_id'], ['performance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'performance_id', name='unique_user_performance')
    )
    op.create_index(op.f('ix_stamp_id'), 'stamp', ['id'], unique=False)
    op.create_table('user_favorite_performance',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['performance_id'], ['performance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'performance_id')
    )
    op.create_table('user_performance_ticketalarm',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['performance_id'], ['performance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'performance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_performance_ticketalarm')
    op.drop_table('user_favorite_performance')
    op.drop_index(op.f('ix_stamp_id'), table_name='stamp')
    op.drop_table('stamp')
    op.drop_index(op.f('ix_review_like_user_id'), table_name='review_like')
    op.drop_index(op.f('ix_review_like_review_id'), table_name='review_like')
    op.drop_index(op.f('ix_review_like_id'), table_name='review_like')
    op.drop_table('review_like')
    op.drop_index(op.f('ix_review_image_review_id'), table_name='review_image')
    op.drop_index(op.f('ix_review_image_id'), table_name='review_image')
    op.drop_table('review_image')
    op.drop_table('performance_artist')
    op.drop_index(op.f('ix_mood_recommendation_id'), table_name='mood_recommendation')
    op.drop_index('ix_mood_id_created_at', table_name='mood_recommendation')
    op.drop_table('mood_recommendation')
    op.drop_table('user_favorite_artist')
    op.drop_table('user_artist_ticketalarm')
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_performance_id'), table_name='performance')
    op.drop_table('performance')
    op.drop_index('ix_notification_user_created', table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_magazine_block_magazine_id'), table_name='magazine_block')
    op.drop_table('magazine_block')
    op.drop_index(op.f('ix_venue_id'), table_name='venue')
    op.drop_table('venue')
    op.drop_index(op.f('ix_user_kakao_id'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_mood_id'), table_name='mood')
    op.drop_table('mood')
    op.drop_index(op.f('ix_magazine_id'), table_name='magazine')
    op.drop_table('magazine')
    op.drop_index(op.f('ix_artist_name'), table_name='artist')
    op.drop_index(op.f('ix_artist_id'), table_name='artist')
    op.drop_table('artist')
    # ### end Alembic commands ###
