"""modify user attribute name

Revision ID: f24f0509d292
Revises: 14e0bc1bf459
Create Date: 2025-07-28 14:44:45.405831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f24f0509d292'
down_revision: Union[str, None] = '14e0bc1bf459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location_enabled', sa.Boolean(), nullable=False))
    op.drop_column('user', 'location_eneabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location_eneabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'location_enabled')
    # ### end Alembic commands ###
